import { writeFileSync, existsSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const SUPABASE_URL = process.env.INPUT_SUPABASE_URL || process.env.VITE_SUPABASE_URL || "https://niscqmgqskzqxwsfxxrs.supabase.co";
const SUPABASE_KEY = process.env.INPUT_SUPABASE_KEY || process.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_hti17zVsM-KrW-0wgSABfw_nqiFPMby";
const COMMIT = process.env.INPUT_COMMIT === "true";

const IMAGES_DIR = resolve(ROOT, "public", "images");
const MAP_FILE = resolve(ROOT, "src", "data", "image-map.ts");

function isGdriveUrl(url) {
  return url && url.includes("drive.google.com");
}

function extractFileId(url) {
  const match = url.match(/\/file\/d\/([^/]+)/);
  return match ? match[1] : null;
}

async function fetchProducts() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/products?select=*`, {
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
    },
  });
  return res.json();
}

function collectUrls(products) {
  const seen = new Set();
  const urls = [];
  for (const p of products) {
    if (isGdriveUrl(p.image) && !seen.has(p.image)) { seen.add(p.image); urls.push(p.image); }
    if (p.images) {
      for (const img of p.images) {
        if (isGdriveUrl(img) && !seen.has(img)) { seen.add(img); urls.push(img); }
      }
    }
    if (p.variants) {
      for (const v of p.variants) {
        if (isGdriveUrl(v.image) && !seen.has(v.image)) { seen.add(v.image); urls.push(v.image); }
        if (v.images) {
          for (const img of v.images) {
            if (isGdriveUrl(img) && !seen.has(img)) { seen.add(img); urls.push(img); }
          }
        }
      }
    }
  }
  return urls;
}

async function downloadThumbnail(fileId) {
  const url = `https://drive.google.com/thumbnail?id=${fileId}&sz=w800`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const buffer = Buffer.from(await res.arrayBuffer());
  const header = buffer.slice(0, 4).toString("hex");
  const isValid = header.startsWith("524946") || header.startsWith("ffd8") || header.startsWith("89504e47");
  if (!isValid) throw new Error("resposta não é uma imagem (requer login?)");
  return buffer;
}

async function main() {
  if (!existsSync(IMAGES_DIR)) mkdirSync(IMAGES_DIR, { recursive: true });

  console.log("Fetching products from Supabase...");
  const products = await fetchProducts();
  const urls = collectUrls(products);
  console.log(`Found ${urls.length} unique Google Drive image URLs`);

  const mapping = {};
  let downloaded = 0;

  for (const url of urls) {
    const fileId = extractFileId(url);
    if (!fileId) { console.warn(`  Skipping, no fileId: ${url.slice(0, 60)}`); continue; }

    const filename = `gdrive-${fileId}.webp`;
    const filepath = resolve(IMAGES_DIR, filename);

    if (existsSync(filepath)) {
      console.log(`  Already exists: ${filename}`);
    } else {
      console.log(`  Downloading ${fileId}...`);
      try {
        const buffer = await downloadThumbnail(fileId);
        writeFileSync(filepath, buffer);
        console.log(`    Saved: ${filename} (${(buffer.length / 1024).toFixed(1)} KB)`);
        downloaded++;
      } catch (err) {
        console.error(`    FAILED: ${err.message}`);
        continue;
      }
    }

    mapping[fileId] = `/images/${filename}`;
  }

  const tsContent = `// Auto-generated by scripts/download-images.mjs\nconst IMAGE_MAP: Record<string, string> = ${JSON.stringify(mapping, null, 2)};\nexport default IMAGE_MAP;\n`;
  writeFileSync(MAP_FILE, tsContent);
  console.log(`\nImage map written: ${Object.keys(mapping).length} entries`);

  if (COMMIT && downloaded > 0) {
    console.log("Committing new images...");
    execSync("git add public/images/*.webp public/images/*.jpg public/images/*.png src/data/image-map.ts", { cwd: ROOT, stdio: "inherit" });
    execSync("git diff --cached --quiet || git commit -m 'chore: sync images from Google Drive [skip ci]'", { cwd: ROOT, stdio: "inherit" });
    execSync("git push", { cwd: ROOT, stdio: "inherit" });
    console.log("Committed and pushed.");
  }
}

main().catch((err) => { console.error(err); process.exit(1); });
